main.py
from flask import Flask
from routes.home import home_route
from routes.register import register_route


app = Flask(__name__) # Inicialização do Flask
app.register_blueprint(home_route) # Ligação com blueprint da página principal
app.register_blueprint(register_route, url_prefix='/register/') # Blueprint página de registro de entradas e saídas

app.run() # Inicialização da página

routes/home.py
"""
Blueprint responsável por organizar todos os dados registrados e organizar em dashboards. Esse módulo utiliza da biblioteca datetime, para salvar o horário local da máquina e utiliza as funções do módulo 'finance', módulo responsável pela extração e cálculo dos dados cadastrados pelo usuário.
"""

from flask import Blueprint, render_template, redirect, url_for, request
from datetime import datetime
import utils.finance as finance

actual_date = datetime.now().strftime("%Y-%m-%d") # Pega a data atual que é usada para redirecionar até a página correspondente

# Criação da blueprint
home_route = Blueprint('home', __name__)

@home_route.route('/') # Rota principal da blueprint, no caso '/'
def home_main():
    # Fatiamaneto de strings
    month = int(actual_date[5:7]) # Salva o mês em uma variável
    year = int(actual_date[0:4]) # Salva o ano em uma variável
    return redirect(url_for('home.home_main_page', month=month, year=year)) # redireciona para a página correspondente ao mes e ano

# Rota principal da blueprint, no caso '/mes/ano'
@home_route.route('/<int:month>/<int:year>') 
def home_main_page(month, year):
    # Pega todos os dados coletados dos registros e extrai para o template 'index.html'
    statistics = finance.json_filtred_date(month, year) 

    month = finance.return_month_text(month)

    # Carrega página principal com os dados e coloca na dashboard principal
    return render_template('index.html', statistics=statistics, month=month, year=year) 

# Rota que filtra os dados escolhidos pelo usuário, no caso mês e ano, e redireciona para a página correspondente
@home_route.route('/search', methods=['POST'])
def search_route():
    # Obtêm informações do formulário e redireciona
    month = request.form.get("select_month") 
    year = request.form.get("select_year")
    return redirect(f'/{month}/{year}')

routes/register.py
from flask import Blueprint, render_template, request, redirect
from datetime import datetime
from utils.datastorage import add_register_json, return_json, remove_register_json, update_register_json, list_years

# Criação da blueprint de registro
register_route = Blueprint('register', __name__)

# Pega a data atual que é usada para redirecionar até a página correspondente
actual_date = datetime.now().strftime("%Y-%m-%d")

# Criação da rota da blueprint, no caso '/register/'
@register_route.route('/<int:month>/<int:year>')
def register_home(month, year):
    REGISTER = return_json() # Salva os dados do arquivo JSON em uma variável
    listYears = list_years()
    return render_template('registration.html', registry=REGISTER, month=month, year=year, actual_date=actual_date, listYears=listYears) # Rendererizar página com as variáveis

@register_route.route('/new', methods=['POST']) # Pegas as informações do formulário do método POST
def add_reigster():
    # Pede as informações do formulário
    description = request.form.get("description")
    value = request.form.get("value")
    category = request.form.get("category")
    type = request.form.get("type")
    date = request.form.get("date")
    # Módulo 'datastorage' responsável por salvar os dados adicionados no JSON
    add_register_json(description, value, category, type, date)
    # Redireciona para a página com mês e ano escolhidos pelo usuário
    return redirect(f'/register/{date[5:7]}/{date[0:4]}')

# Rota responsável por deletar um registro
@register_route.route('/delete/<int:id>/<int:month>/<int:year>', methods=['POST'])
def remover_register(id, month, year):
    #  Módulo 'datastorage' que é responsável por tirar as informações do JSON
    remove_register_json(id)
    # Redireciona para o mês e ano atual
    return redirect(f'/register/{month}/{year}')

# Rota de edição do registro pelo id
@register_route.route('/edit/<int:id>', methods=['POST'])
def edit_register(id):
    # Retorna toda a base dados
    REGISTER = return_json()

    # Cria uma variável com apenas o id selecionado
    registry = REGISTER[id-1]

    # Renderiza toda a página apenas com os dados do id atual
    return render_template('register_edit.html', registry=registry)

# Rota de atualização atráves do id
@register_route.route('/update/<int:id>', methods=['POST'])
def update_register(id):
    # Salva todos os dados fornecido pelo usuário nos formulários
    description = request.form.get("description")
    value = request.form.get("value")
    category = request.form.get("category")
    type = request.form.get("type")
    date = request.form.get("date")

    # Chama função que atualiza o arquivo JSON
    update_register_json(id, description, value, category, type, date)

    # Redirecionar para o mes e ano daquele determinado registro
    return redirect(f'/register/{date[5:7]}/{date[0:4]}')

# Rota para o filtro dos registro por mês e ano
@register_route.route('/search', methods=['POST'])
def search_route():
    # Salva entradas do usuário
    month = request.form.get("select_month")
    year = request.form.get("select_year")

    # Redireciona para a página correspondente ao mês e ano
    return redirect(f'/register/{month}/{year}')

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if month == 0 %}
        <title>Home - Geral/{{ year }}</title>
    {% else %}
        <title>Home - {{ month }}/{{ year }}</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('register.register_home', month=statistics.date[5:7], year=statistics.date[0:4]) }}">Registros</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row g-4">
            <div class="col-md-4">
                <h2 class="mb-4">Resumo Geral</h2>
                {% if month == 0 %}
                    <h2>{{ year }}</h2>
                {% else %}
                     <h2>{{ month }}</h2>
                {% endif %}
                {% include "partials/filter_home.html" %}
            </div>
        </div>
        <div class="row g-4">
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Saldo</h5>
                        <p class="display-6 text-success">R$ {{ statistics.wallet|round(2) }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Entradas</h5>
                        <p class="display-6 text-success">R$ {{ statistics.total[0]|round(2) }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body d-flex justify-content-between align-items-center">
                        <div>
                            <h5 class="card-title">Saídas</h5>
                            <p class="display-6 text-danger">R$ {{ statistics.total[1]|round(2)|abs }}</p> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-4">
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Necessidades</h5>
                        <p class="display-6">{{ statistics.types.Necessidade|round(2)}}%</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Desejos</h5>
                        <p class="display-6">{{ statistics.types.Desejos|round(2)}}%</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Poupança</h5>
                        <p class="display-6">{{ statistics.types.Poupança|round(2)}}%</p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row g-4">
                <div class="col-md-4">
                    {% if statistics.wallet != 0 %}
                        {% if statistics.status == 'Controlado' %}
                            <h1>Status: <span class="text-success">{{  statistics.status  }}</span></h1>
                        {% elif statistics.status == 'Negativado' %}
                            <h1>Status: <span class="text-danger">{{  statistics.status  }}</span></h1>
                        {% else %}
                            <h1>Status: <span class="text-warning">{{  statistics.status  }}</span></h1>
                        {% endif %}
                    {% else %}
                        <h1>Status: ---</h1>
                    {% endif %}  
                    {% include "partials/wallet_bars.html" %}
                </div>
                <div class="col-md-4">
                    {% if statistics.total[0] != 0 or statistics.total[1] != 0 %}
                        <p class="display-6">Você gastou {{ statistics.prct|round(1) }}% do que recebe</p>
                    {% else %}
                        <p class="display-6">Nenhum dado foi cadastrado para esse perído :(</p>
                    {% endif %}
                    
                </div>
                <div class="col-md-4">
                    {% include "partials/graphic_pizza.html" %}
                </div>
            </div>
        </div>
        <hr>
        <h2>Invesimentos</h2>
        <div class="card-body">
            {% if month != 0 %}
                <h5 class="card-title">Este mês:</h5>
            {% else %}
                <h5 class="card-title">Este ano:</h5>
            {% endif %}
            
            <p class="display-6 text-success">R$ {{ statistics.monthInvestments|round(2) }}</p>
        </div>
        {% include "partials/investment_line.html" %}
        <hr class="my-5">

        <h3>Categorias Mais Gastas</h3>
        <table class="table table-striped mt-3 shadow-sm bg-white">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Categoria</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                {% for i in range(0, statistics.rankingCategories | length) %}
                    <tr>
                        {% if statistics.rankingCategories[i][1] <= 0 %}
                            <td>{{i+1}}º</td>
                            <td>{{ statistics.rankingCategories[i][0] }}</td>
                            <td>R$ {{ statistics.rankingCategories[i][1]|round(2)|abs }}</td>
                        {% endif %} 
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr>
</body>
</html>

templates/partials/filter_home.html
<form action="{{ url_for('home.search_route')}}" method="POST">
    <div class="row">
        <div class="col-4 mb-3">
            <select name="select_month" class="form-select">
                <option value="0">Todos</option>
                <option value="01" {% if month == "Janeiro" %}selected{% endif %}>Jan</option>
                <option value="02" {% if month == "Fevereiro" %}selected{% endif %}>Fev</option>
                <option value="03" {% if month == "Março" %}selected{% endif %}>Mar</option>
                <option value="04" {% if month == "Abril" %}selected{% endif %}>Abr</option>
                <option value="05" {% if month == "Maio" %}selected{% endif %}>Mai</option>
                <option value="06" {% if month == "Junho" %}selected{% endif %}>Jun</option>
                <option value="07" {% if month == "Julho" %}selected{% endif %}>Jul</option>
                <option value="08" {% if month == "Agosto" %}selected{% endif %}>Ago</option>
                <option value="09" {% if month == "Setembro" %}selected{% endif %}>Set</option>
                <option value="10" {% if month == "Outubro" %}selected{% endif %}>Out</option>
                <option value="11" {% if month == "Novembro" %}selected{% endif %}>Nov</option>
                <option value="12" {% if month == "Dezembro" %}selected{% endif %}>Dez</option> 
            </select>
        </div>
        <div class="col-4 mb-3">
            <select name="select_year" class="form-select">
                {% for i in range(0, statistics.listYears | length)  %}
                    <option value="{{ statistics.listYears[i] }}" {% if year == statistics.listYears[i] %}selected{% endif %}>{{ statistics.listYears[i] }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-4 mb-3">
            {% if statistics.listYears | length == 0 %}
                <button type="button" class="btn btn-outline-secondary disabled">Ok</button>
            {% else %}
                <button type="submit" class="btn btn-outline-secondary">Ok</button>
            {% endif %}
        </div>
    </div>
</form>

templates/partials/filter_registry.html
<form action="{{ url_for('register.search_route')}}" method="POST">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <div class="col-4">
                                <select name="select_month" class="form-select">
                                    <option value="0" {% if month == 1 %}selected{% endif %}>Todos</option>
                                    <option value="01" {% if month == 1 %}selected{% endif %}>Jan</option>
                                    <option value="02" {% if month == 2 %}selected{% endif %}>Fev</option>
                                    <option value="03" {% if month == 3 %}selected{% endif %}>Mar</option>
                                    <option value="04" {% if month == 4 %}selected{% endif %}>Abr</option>
                                    <option value="05" {% if month == 5 %}selected{% endif %}>Mai</option>
                                    <option value="06" {% if month == 6 %}selected{% endif %}>Jun</option>
                                    <option value="07" {% if month == 7 %}selected{% endif %}>Jul</option>
                                    <option value="08" {% if month == 8 %}selected{% endif %}>Ago</option>
                                    <option value="09" {% if month == 9 %}selected{% endif %}>Set</option>
                                    <option value="10" {% if month == 10 %}selected{% endif %}>Out</option>
                                    <option value="11" {% if month == 11 %}selected{% endif %}>Nov</option>
                                    <option value="12" {% if month == 12 %}selected{% endif %}>Dez</option> 
                                </select>
                        </div>
                        <div class="col-4">
                            <select name="select_year" class="form-select">
                                {% for i in range(0, listYears | length)  %}
                                    <option value="{{ listYears[i] }}" {% if year == listYears[i] %}selected{% endif %}>{{ listYears[i] }}</option>
                                    {% endfor %}
                            </select>
                        </div>
                        <div class="col-4">
                            {% if listYears | length == 0 %}
                            <button type="button" class="btn btn-outline-secondary disabled">Ok</button>
                            {% else %}
                                <button type="submit" class="btn btn-outline-secondary">Ok</button>
                            {% endif %}
                        </div>
                </div>
            </form>

templates/partials/graphic_pizza.html
<canvas id="graphic-pizza"></canvas>

<script>
  const ctxPizza = document.getElementById('graphic-pizza');
  let necessidade = JSON.parse('{{ statistics.types.Necessidade|round(2)}}');
  let desejos = JSON.parse('{{ statistics.types.Desejos|round(2)}}');
  let poupanca = JSON.parse('{{ statistics.types.Poupança|round(2)}}');

  new Chart(ctxPizza, {
    type: 'doughnut',
    data: {
      labels: ['Necessidade', 'Desejos', 'Poupança'],
      datasets: [{
        label: '%',
        data: [necessidade, desejos, poupanca],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

templates/partials/investment_line.html
<canvas id="graphic-line"></canvas>

<script>
  const ctxLine = document.getElementById('graphic-line');
  let investiments = JSON.parse('{{ statistics.lineGraphic }}');

  new Chart(ctxLine, {
    type: 'line',
    data: {
      labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
      datasets: [{
        label: 'R$',
        data: investiments,
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

templates/register_edit.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Registro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('home.home_main')}}">Editar Registro</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('register.register_home', month=registry.date[5:7], year=registry.date[0:4]) }}">Registros</a>
                    </li>
            </div>
        </div>
    </nav>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm rounded">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">Editar Registro</h5>
                    </div>
                    <div class="card-body">
                        <form action="/register/update/{{ registry.id }}" method="POST">
                            <div class="mb-3">
                                <label class="form-label">Descrição</label>
                                <input 
                                    type="text"
                                    class="form-control"
                                    name="description"
                                    value="{{ registry.description }}"
                                    required
                                >
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Valor</label>
                                <input 
                                    type="number"
                                    step="0.01"
                                    class="form-control"
                                    name="value"
                                    value="{{ registry.value }}"
                                    required
                                >
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Categoria</label>
                                <select class="form-select" name="category" required>
                                    <option value="Alimentação" {% if registry.category == "Alimentação" %}selected{% endif %}>Alimentação</option>
                                    <option value="Assinaturas" {% if registry.category == "Assinaturas" %}selected{% endif %}>Assinaturas</option>
                                    <option value="Contas" {% if registry.category == "Contas" %}selected{% endif %}>Contas</option>
                                    <option value="Investimentos" {% if registry.category == "Investimentos" %}selected{% endif %}>Investimentos</option>
                                    <option value="Lazer" {% if registry.category == "Lazer" %}selected{% endif %}>Lazer</option>
                                    <option value="Mercado" {% if registry.category == "Mercado" %}selected{% endif %}>Mercado</option>
                                    <option value="Necessidades" {% if registry.category == "Necessidades" %}selected{% endif %}>Necessidades</option>
                                    <option value="Renda Extra" {% if registry.category == "Renda Extra" %}selected{% endif %}>Renda Extra</option>
                                    <option value="Roupas" {% if registry.category == "Roupas" %}selected{% endif %}>Roupas</option>
                                    <option value="Saúde" {% if registry.category == "Saúde" %}selected{% endif %}>Saúde</option>
                                    <option value="Transporte" {% if registry.category == "Transporte" %}selected{% endif %}>Transporte</option>
                                    <option value="Trabalho" {% if registry.category == "Trabalho" %}selected{% endif %}>Trabalho</option>
                                    <option value="Outros" {% if registry.category == "Outros" %}selected{% endif %}>Outros</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Tipo</label>
                                <select class="form-select" name="type" required>
                                    <option value="Renda"{% if registry.type == "Renda" %}selected{% endif %}>Renda</option>
                                    <option value="Necessidade"{% if registry.type == "Necessidade" %}selected{% endif %}>Necessidade</option>
                                    <option value="Desejos"{% if registry.type == "Desejos" %}selected{% endif %}>Desejos</option>
                                    <option value="Poupança"{% if registry.type == "Poupança" %}selected{% endif %}>Poupança</option>
                                </select>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Data</label>
                                <input type="date" name="date" class="form-control" value="{{ registry.date }}" required>
                            </div>
                            <div class="d-flex justify-content-between mt-4">
                                <a href="{{ url_for('register.register_home', month=registry.date[5:7], year=registry.date[0:4]) }}" class="btn btn-outline-secondary">Cancelar</a>
                                <button class="btn btn-success" type="submit">Salvar Alterações</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

templates/registration.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if month == 0 %}
        <title>Home - Geral/{{ year }}</title>
    {% else %}
        <title>Home - {{ month }}/{{ year }}</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Registros</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row justify-content-between">
        <div class="col-4">
            <h2 class="mb-4">Lista de Registros</h2>
        </div>
        <div class="col-4">
            {% include "partials/filter_registry.html" %}
        </div>
    </div>
    
    <table class="table table-striped bg-white shadow-sm">
        <thead>
            <tr>
                <th>ID</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Categoria</th>
                <th>Tipo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% if month == 0 %}
                {% for i in registry %}
                    {% if year == i.date[0:4]|int %}
                        <tr>    
                            <td>{{ i.id }}</td>
                            <td>{{ i.description }}</td>
                            {% if i.value < 0 %}
                                <td class="text-danger">R$ {{ i.value|abs|round(2) }}</td>
                            {% else %}
                                <td class="text-success">R$ {{ i.value|round(2) }}</td>
                            {% endif %}
                            <td>{{ i.category }}</td>
                            <td>{{ i.type }}</td>
                                <td>
                                    <form action="/register/edit/{{ i.id }}" method="POST">
                                        <button class="btn btn-success btn-sm">Editar</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ url_for('register.remover_register', id=i.id, month=month, year=year) }}" method="POST">
                                        <button class="btn btn-danger btn-sm">Remover</button>
                                    </form>
                                </td>
                            
                            <td>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
            {% else %}
                {% for i in registry %}
                    {% if month == i.date[5:7]|int and year == i.date[0:4]|int %}
                        <tr>    
                            <td>{{ i.id }}</td>
                            <td>{{ i.description }}</td>
                            {% if i.value < 0 %}
                                <td class="text-danger">R$ {{ i.value|abs|round(2) }}</td>
                            {% else %}
                                <td class="text-success">R$ {{ i.value|round(2) }}</td>
                            {% endif %}
                            <td>{{ i.category }}</td>
                            <td>{{ i.type }}</td>
                                <td>
                                    <form action="/register/edit/{{ i.id }}" method="POST">
                                        <button class="btn btn-success btn-sm">Editar</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ url_for('register.remover_register', id=i.id, month=month, year=year) }}" method="POST">
                                        <button class="btn btn-danger btn-sm">Remover</button>
                                    </form>
                                </td>
                            
                            <td>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
            
        </tbody>
    </table>

    <hr class="my-4">

    <h3>Adicionar novo registro</h3>

    <form class="bg-white p-4 shadow-sm rounded" action="{{ url_for('register.add_reigster')}}" method="POST">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type="text" name="description" class="form-control" placeholder="Ex: Mercado" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="number" name="value" step="0.01" class="form-control" placeholder="Ex: 50.00" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Categoria</label>
            <select class="form-select" name="category" required>
                <option value="">Selecione</option>
                <option value="Alimentação">Alimentação</option>
                <option value="Assinaturas">Assinaturas</option>
                <option value="Contas">Contas</option>
                <option value="Investimentos">Investimentos</option>
                <option value="Lazer">Lazer</option>
                <option value="Mercado">Mercado</option>
                <option value="Necessidades">Necessidades</option>
                <option value="Renda Extra">Renda Extra</option>
                <option value="Roupas">Roupas</option>
                <option value="Saúde">Saúde</option>
                <option value="Transporte">Transporte</option>
                <option value="Trabalho">Trabalho</option>
                <option value="Outros">Outros</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Tipo</label>
            <select class="form-select" name="type" required>
                <option value="">Selecione</option>
                <option value="Renda">Renda</option>
                <option value="Necessidade">Necessidade</option>
                <option value="Desejos">Desejos</option>
                <option value="Poupança">Poupança</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="date" name="date" class="form-control" value="{{ actual_date }}" required>
        </div>
        <button type="submit" class="btn btn-primary w-100">Adicionar Registro</button>
    </form>
</div>
</body>
</html>